### PR TITLE
Sub-site prep

### PR DESCRIPTION
**Pull request by autumnfound**

### CODE REVIEW

**Comment by chrisguindon** [comment]
New requirements:

1. Move the current homepage, which is for the 2019 event, to https://www.osdforum.org/2019
1.1 Implement sponsor text change: https://github.com/openhwgroup/osdforum.org/issues/66

2. Remove the save the date section at the bottom of the 2019 event page + remove Registration is limited, so don't delay - register today! from the about osdforum section.

3. add a Next Up: OSDForum 2020 link in the header of the 2019 website

4. Create a very simple save the date page for 2020 based off the layout of 2019.
4.1 Content is based off this request: https://github.com/openhwgroup/osdforum.org/issues/65
4.2 Keep the Sponsored by section and remove all sponsors except CMC, EF & OpenHW
4.3 remove venue section for now + remove location from the header

5. Add a Past Events menu item with a drop down menu for OSDForum 2019.

**Comment by chrisguindon** [comment]
Feedback from Ric:

1 – change the date to September 15th, 2020 (yes, back to 1 day format)

2 – remove the following text in the description paragraph “The agenda also includes a hands on bring up session using a RISC-V based development board that attendees can keep. Made possible by the generous support of our sponsors, the OSDForum is a non-profit event with low attendee fees of $50 for industry attendees and $25 for academic attendees (includes the full day of talks, breaks, lunch and a RISC-V development board).”

3 – remove the following text under the circuit board picture (keep the picture, but remove text) “RISC-V dev board attendees will keep”

**Comment by autumnfound** [comment]
@chrisguindon Fixed according to feedback

**Comment by chrisguindon** [comment]
thanks @autumnfound

**Pull request merged**
