### PR TITLE
add slides and youtube videos

### LINKED ISSUE #97: Slides and Videos
Pls post the PDFs and links to Videos for each of the talks shown on the agenda https://www.osdforum.org/ (11 talks with slides & videos).  Note, there are no slides or video for the 9am talk.  Slide PDFs are in the archive linked here [https://drive.google.com/file/d/1uPJM8ciABbuQ5pxfnCDF4WoITBfCP-of/view?usp=drivesdk and video urls are shown below in chronological order.  Also, the chronological video playlist is shown here https://www.youtube.com/playlist?list=PL5xxtziB58VlMEtfCjIcd2mN-Shq5qE93

1 https://youtu.be/_D-ZUeqd4Hs
2 https://youtu.be/3XKzTjNyHT8
3 https://youtu.be/C3k8z9nMvII
4 https://youtu.be/jPS3Urqmd4Q
5 https://youtu.be/dxO72R-dBWk
6A https://youtu.be/b_rWumk3Fic
6B https://youtu.be/xG-5XMfdYIQ
6C https://youtu.be/8nQjKbpejZo 
7 https://youtu.be/PeGBvAe0yHw
8 https://youtu.be/AOQ50uhhqSc
9 https://youtu.be/0hiCYSOK-ac

### PR DESCRIPTION
**Pull request by flora8984461**
Fix #97 

Signed-off-by: Yi Liu <yi.liu@eclipse-foundation.org>

### CODE REVIEW

**Review by autumnfound — APPROVED** [review]

**Comment by rickoco** [comment]
@flora8984461 @autumnfound - the deploy preview looks great except there are “play” buttons at the 9am Welcome, 10:45am break, 12:15pm lunch and 5:30pm adjourn when in fact there are no video recordings to be played at these times.  Can we pls delete the play buttons here?

**Comment by autumnfound** [comment]
> @flora8984461 @autumnfound - the deploy preview looks great except there are “play” buttons at the 9am Welcome, 10:45am break, 12:15pm lunch and 5:30pm adjourn when in fact there are no video recordings to be played at these times. Can we pls delete the play buttons here?

This is an issue in our base theme as we need to add a check to not include that for non-content session blocks. If getting this content up is time-sensitive, I would recommend we merge this now and fix this with a patch after the fact.

**Comment by chrisguindon** [comment]
@autumnfound I am currently working with @flora8984461 on this! 

I don't want to merge this in the current state.

**Review by chrisguindon — CHANGES_REQUESTED** [review]
We need to fix the video links before merging this PR.

**Comment by chrisguindon** [comment]
@rickoco Can you confirm that we have permission from slides author to add to our website? 

I assume so, but just want to make sure with you before we merge this in!

**Comment by chrisguindon** [comment]
@rickoco,

@flora8984461 made a fix to our agenda shortcode:
https://deploy-preview-98--eclipsefdn-osdforum.netlify.app/

Also, we are ready to go live once confirm that we have permission to commit the slides to the website!

**Comment by rickoco** [comment]
@chrisguindon - yes we have speaker agmts in place that @annejacko looked after

**Comment by chrisguindon** [comment]
> @chrisguindon - yes we have speaker agmts in place that @annejacko looked after

@annejacko confirmed that we are missing 1 aggrement. @annejacko please let us know here once we are good to merge this!

**Comment by rickoco** [comment]
@chrisguindon - you were copied on the email reply from Embecosm with their permission.  Pls deploy...

**Comment by chrisguindon** [comment]
@rickoco Thank you!

**Pull request merged**
